# ==========================================
# pytest.ini - Pytest Configuration File
# ==========================================

[pytest]

addopts =
    # ------------------------------
    # General Options
    # ------------------------------
    -v -s


    # ------------------------------
    #  Reports (Debugging)
    # ------------------------------

    --html=reports/myreport.html --self-contained-html --capture=tee-sys
    --alluredir=reports/allure-results
    # ones we ran the execution, to display ALLURE REPORTS, we must run two commands:
    # 1. TO GENERATE THE REPORTS -> allure generate reports/allure-results
    # 2. TO VIEW THE REPORTS -> allure serve allure-report

    # ------------------------------
    # Parallel Execution (enable two workers)
    # ------------------------------
    #-n=1
    #--numprocesses=2

    # ------------------------------
    # Test Grouping (Markers)
    # ------------------------------
    # Enable one of the below commands when running pytest from cmd line using only cmd --> pytest tests:
    # -m "sanity"
    # -m "regression"
    # -m "post"
    # -m "sanity or regression"
    # -m "sanity and regression"
    # -m "auth"
    # -m "sanity and not regression"
    # -m "regression and not sanity"
    # -m "sanity or regression"
     -m "end_to_end"

    # ------------------------------
    # Flaky Test Handling
    # ------------------------------
    #--reruns 2
    #--reruns-delay 2


# ------------------------------
# Custom Markers
# ------------------------------
markers =
    sanity: marks a sanity test (basic quick check)
    regression: marks a regression test (full end-to-end validation)
    post: marks only POST test
    end_to_end: marks an end-to-end test
    auth: marks auth tests
